# Define the R scripts to run
R_SCRIPTS := simulation1.R simulation1b.R simulation2.R simulation3.R simulation4.R simulation4a.R

# Default target: run all simulations
all: run_simulations 

# Target to run all R scripts
run_simulations:
	Rscript run_simulations.R
