name: Build and Publish Docker Image

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-docker-image.yml'
      - 'VK/thesis/**'
      - 'VK/simulation/results/**'
      - 'LK/thesis.qmd'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get short SHA of LK/thesis.qmd
        id: get-file-sha
        run: |
          LK_SHA=$(git log -n 1 --format=format:%h --full-diff -- LK/thesis.qmd)
          echo "Short File SHA of LK/thesis.qmd: $LK_SHA"
          echo "LK_SHA=$LK_SHA" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/quarto-render:latest
          build-args: |
            LK_SHA=${{ env.LK_SHA }}  # Pass the short file SHA as a build argument
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          load: false

      - name: Move New Cache
        if: success()
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
