name: Render and Publish Thesis

on:
  push:
    branches:
      - main

jobs:
  render-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Pull Docker image
        run: |
          docker run --pull always ghcr.io/${{ github.repository_owner }}/quarto-render:latest

      - name: Render Thesis
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/VK:/home/rstudio/VK \
            ghcr.io/${{ github.repository_owner }}/quarto-render:latest \
            quarto render thesis.qmd

      - name: List site contents
        run: |
          ls -R VK/thesis/_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: VK/thesis/_site
