name: Render and Publish Thesis

on:
    push:   
      branches:
        - presentation

jobs:
  render-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/quarto-render:latest

      - name: Get UID and GID
        id: uid_gid
        run: |
          echo "uid=$(id -u)" >> $GITHUB_OUTPUT
          echo "gid=$(id -g)" >> $GITHUB_OUTPUT

      - name: Render Thesis
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/VK:/home/rstudio/VK \
            --user ${{ steps.uid_gid.outputs.uid }}:${{ steps.uid_gid.outputs.gid }} \
            ghcr.io/${{ github.repository_owner }}/quarto-render:latest

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: VK/thesis/_site
