on:
  push:
    branches: main
  registry_package:
    types: [published, updated]
  workflow_dispatch:

name: Render and publish Thesis and Presentation

jobs:
  imagename:
    runs-on: ubuntu-latest
    outputs:
      lowercase: ${{ steps.lowercase.outputs.test }}
    steps:
      - name: Convert the repo name to lowercase
        id: lowercase
        run: echo "::set-output name=test::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"

  publish-thesis:
    needs: imagename
    runs-on: ubuntu-latest
    container: ghcr.io/${{ needs.imagename.outputs.lowercase }}:main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: list files in the repository recursively
        run: ls -R
      
      - name: set working directory
        run: cd VK
        
      - name: list files in the repository recursively
        run: ls -R

      - name: Render Thesis
        run: quarto render thesis/thesis.qmd

      - name: Publish Thesis to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: VK/thesis/_site
          folder-to-dest: thesis
          token: ${{ secrets.GH_TOKEN }}
          clean: false

  publish-presentation:
    runs-on: ubuntu-latest
    needs: imagename
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install Required R Packages
        run: |
          Rscript -e 'install.packages(c("knitr", "rmarkdown", "dplyr", "ggplot2", "tidyr", "kableExtra"), repos = "https://cran.rstudio.com")'

      - name: Render Presentation
        run: quarto render VK/presentation

      - name: Publish Presentation to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: VK/presentation/_site
          folder-to-dest: presentation
          token: ${{ secrets.GH_TOKEN }}
          clean: false
