name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  knit-and-publish-thesis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository_owner }}/quarto-render:latest

      - name: Render Quarto Thesis Document
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/VK/thesis \
          ghcr.io/${{ github.repository_owner }}/quarto-render:latest \
          quarto render thesis.qmd

      - name: Deploy Thesis to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./VK/thesis/_site
          destination_dir: . 

  build-deploy-presentation:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install Required R Packages
        run: |
          Rscript -e 'install.packages(c(
            "knitr", 
            "rmarkdown", 
            "dplyr", 
            "tidyr", 
            "kableExtra", 
            "ggplot2"
          ), repos = "https://cran.rstudio.com")'
        env:
          R_LIBS_USER: ${{ env.R_LIBS_USER }}

      - name: Render Quarto Presentation
        run: quarto render VK/presentation

      - name: Publish Presentation to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: VK/presentation
          dest: presentation
          clean: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
