name: Quarto Publish Thesis

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/valentinkm/quarto-render:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Git for Publishing
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Render Quarto Project
        run: quarto render thesis/thesis.qmd

      - name: Publish Thesis
        run: |
          quarto publish gh-pages thesis --no-browser --no-render
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}