name: Publish Thesis and Presentation

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed

jobs:
  publish-thesis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository_owner }}/quarto-render:latest

      - name: Render Thesis Document
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/VK:/home/rstudio/VK \
          -v ${{ github.workspace }}/LK:/home/rstudio/LK \
          -w /home/rstudio/VK/thesis \
          ghcr.io/${{ github.repository_owner }}/quarto-render:latest \
          quarto render thesis.qmd

      - name: Check if _site directory exists
        run: |
          if [ ! -d "./VK/thesis/_site" ]; then
            echo "_site directory does not exist. Rendering failed."
            exit 1
          fi

      - name: Deploy Thesis to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./VK/thesis/_site
          destination_dir: thesis
        env:
          ACTIONS_STEP_DEBUG: true

  publish-presentation:
    runs-on: ubuntu-latest
    needs: publish-thesis
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install Required R Packages
        run: |
          Rscript -e 'install.packages(c(
            "knitr", 
            "rmarkdown", 
            "dplyr", 
            "tidyr", 
            "kableExtra", 
            "ggplot2"
          ), repos = "https://cran.rstudio.com")'

      - name: Render Presentation
        run: quarto render VK/presentation

      - name: Deploy Presentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./VK/presentation/_site
          destination_dir: presentation
        env:
          ACTIONS_STEP_DEBUG: true
