name: Quarto Publish Thesis

on:
    push:
      branches:
        - main
    workflow_run:
      workflows: ["Build and Publish Docker Image"]
      types:
        - completed

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/valentinkm/quarto-render:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Install LaTeX (TeX Live with xelatex)
        run: |
          apt-get update
          apt-get install -y \
            texlive-xetex \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-latex-extra \
            texlive-lang-all

      - name: Render Quarto Project
        working-directory: /VK
        run: quarto render thesis/thesis.qmd

      - name: Publish Thesis
        working-directory: /VK
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: thesis  # relative to /VK
          render: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}