name: Publish Thesis and Presentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-thesis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository_owner }}/quarto-render:latest

      - name: Render Thesis Document
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/VK/thesis \
          ghcr.io/${{ github.repository_owner }}/quarto-render:latest \
          quarto render thesis.qmd

      - name: Deploy Thesis to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./VK/thesis/_site
          destination_dir: thesis
          clean: false

  publish-presentation:
    runs-on: ubuntu-latest
    needs: publish-thesis
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install Required R Packages
        run: |
          Rscript -e 'install.packages(c(
            "knitr", 
            "rmarkdown", 
            "dplyr", 
            "tidyr", 
            "kableExtra", 
            "ggplot2"
          ), repos = "https://cran.rstudio.com")'

      - name: Render Presentation
        run: quarto render VK/presentation

      - name: Deploy Presentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./VK/presentation/_site
          destination_dir: presentation
          clean: false
