name: Quarto Publish Thesis

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'VK/Dockerfile'
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed

jobs:
  build-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/quarto-render:latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Git for Publishing
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Render Quarto Project
        run: quarto render thesis/thesis.qmd

      - name: Publish Thesis
        run: |
          quarto publish gh-pages thesis --no-browser --no-render
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}