on:
  push:
    branches: main
  registry_package:
    types: [published, updated]
  workflow_dispatch:

name: Render and publish Thesis and Presentation

jobs:
  # Convert the repository name to lowercase for image name
  imagename:
    runs-on: ubuntu-latest
    outputs:
      lowercase: ${{ steps.lowercase.outputs.test }}
    steps:
      - name: Convert the repo name to lowercase
        id: lowercase
        run: echo "::set-output name=test::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"

  # Publish the thesis using the custom Docker container
  publish-thesis:
    runs-on: ubuntu-latest
    needs: imagename
    container: ghcr.io/${{ needs.imagename.outputs.lowercase }}:main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Render Thesis
        working-directory: /VK
        run: quarto render thesis/thesis.qmd

      - name: Publish Thesis to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: VK/thesis/_site
          folder-to-dest: thesis  # Ensure it goes to 'thesis' folder
          token: ${{ secrets.GH_TOKEN }}
          clean: false  # Ensure no conflicts with other pages

  # Publish the presentation (not in Docker)
  publish-presentation:
    runs-on: ubuntu-latest
    needs: imagename
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install Required R Packages
        run: |
          Rscript -e 'install.packages(c("knitr", "rmarkdown", "dplyr", "ggplot2"), repos = "https://cran.rstudio.com")'

      - name: Render Presentation
        run: quarto render VK/presentation

      - name: Publish Presentation to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: VK/presentation/_site
          folder-to-dest: presentation  # Ensure it goes to 'presentation' folder
          token: ${{ secrets.GH_TOKEN }}
          clean: false
