name: Quarto Publish Thesis and Presentation

on:
  push:
    branches:
      - main

jobs:
  build-thesis:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/valentinkm/quarto-render:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Git and LaTeX (TeX Live with xelatex)
        run: |
          apt-get update
          apt-get install -y git texlive-xetex texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra texlive-lang-all

      - name: Render Thesis (Docker with LaTeX)
        working-directory: /VK
        run: quarto render thesis/thesis.qmd

      - name: Publish Thesis to gh-pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: VK/thesis/_site
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  build-presentation:
    runs-on: ubuntu-latest
    needs: build-thesis  # Ensures thesis is built before presentation
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R for Presentation
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Cache R Packages for Presentation
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install Required R Packages for Presentation
        run: |
          Rscript -e 'install.packages(c(
            "knitr", 
            "rmarkdown", 
            "dplyr", 
            "tidyr", 
            "kableExtra", 
            "ggplot2"
          ), repos = "https://cran.rstudio.com")'
        env:
          R_LIBS_USER: ${{ env.R_LIBS_USER }}

      - name: Render Presentation (Non-Docker)
        run: quarto render VK/presentation

      - name: Publish Presentation to gh-pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: VK/presentation/_site
          dest: presentation
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
