name: Publish Thesis

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  knit-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository_owner }}/quarto-render:latest

      - name: Render Quarto document
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/thesis \
          ghcr.io/${{ github.repository_owner }}/quarto-render:latest \
          quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./thesis/_site
          destination_dir: .
