name: Publish Thesis and Presentation

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed

jobs:
  render-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Pull Docker image
        run: |
          docker run --pull always ghcr.io/${{ github.repository_owner }}/quarto-render:latest

      - name: Render Thesis
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/VK:/home/rstudio/VK \
            ghcr.io/${{ github.repository_owner }}/quarto-render:latest \
            quarto render thesis.qmd

      - name: List site contents
        run: |
          ls -R VK/thesis/_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: VK/thesis/_site

  publish-presentation:
    runs-on: ubuntu-latest
    needs: render-and-publish

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install Required R Packages
        run: |
          Rscript -e 'install.packages(c(
            "knitr", 
            "rmarkdown", 
            "dplyr", 
            "tidyr", 
            "kableExtra", 
            "ggplot2"
          ), repos = "https://cran.rstudio.com")'

      - name: Render Presentation
        run: quarto render VK/presentation

      - name: Deploy Presentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./VK/presentation/_site
          destination_dir: presentation
        env:
          ACTIONS_STEP_DEBUG: true