name: Minimal Simulation Replication

on:
  push:
    paths:
      - 'VK/simulation/**'
      - '.github/workflows/simulation.yml'
    paths-ignore:
      - 'VK/simulation/results/**'
      - 'VK/simulation/results/replic/**'

env:
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/simulation_image:latest
  RESULTS_DIR: VK/simulation/results_replic

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get UID and GID
        run: |
          echo "UID=$(id -u)" >> $GITHUB_ENV
          echo "GID=$(id -g)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./VK/simulation
          build-args: |
            USER_ID=${{ env.UID }}
            GROUP_ID=${{ env.GID }}
          tags: ${{ env.DOCKER_IMAGE_NAME }}
          push: true

  run_simulation_in_docker:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git authentication
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Prepare results directory
        run: mkdir -p ${{ github.workspace }}/$RESULTS_DIR

      - name: Run simulation in Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/$RESULTS_DIR:/simulation/results_replic \
            ${{ env.DOCKER_IMAGE_NAME }}

      - name: List results directory contents
        run: ls -la ${{ github.workspace }}/$RESULTS_DIR

      - name: Commit and create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'Add simulation results'
          branch: 'simulation-results/${{ github.run_id }}'
          title: 'Add simulation results'
          body: 'This PR adds the latest simulation results.'
          token: ${{ secrets.GH_TOKEN }}
          delete-branch: true
