name: Simulation Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Define the Docker image name following the GitHub Container Registry naming convention
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/simulation_image:latest
  RESULTS_DIR: VK/simulation/results_replic
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Docker Buildx (for multi-platform builds if needed)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    # 4. Build and push the Docker image from VK/simulation directory
    - name: Build and push Docker image
      run: |
        docker build -t $DOCKER_IMAGE_NAME ./VK/simulation
        docker push $DOCKER_IMAGE_NAME

  run_simulation_in_docker:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image

    steps:
    # 1. Check out the code again
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Run the Docker container and execute the simulation
    - name: Run simulation in Docker container
      run: |
        docker pull $DOCKER_IMAGE_NAME
        docker run --rm -v ${{ github.workspace }}/VK/simulation/results_replic:/simulation/results_replic $DOCKER_IMAGE_NAME

    # 3. Add and commit the results generated from the simulation
    - name: Commit and push results
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "GitHub Actions"
        cd ${{ github.workspace }}/VK/simulation/results_replic
        git add .
        git commit -m "Add simulation results"
        git push origin main
