name: Simulation Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/simulation_image:latest
  RESULTS_DIR: VK/simulation/results_replic

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Get UID and GID of the GitHub Actions runner
      - name: Get UID and GID
        run: |
          echo "UID=$(id -u)" >> $GITHUB_ENV
          echo "GID=$(id -g)" >> $GITHUB_ENV

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      # 5. Build and push the Docker image to GHCR
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./VK/simulation
          build-args: |
            USER_ID=${{ env.UID }}
            GROUP_ID=${{ env.GID }}
          tags: ${{ env.DOCKER_IMAGE_NAME }}
          push: true

  run_simulation_in_docker:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image

    steps:
      # 1. Check out the code without persisting default credentials
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 2. Set up Git authentication with GH_TOKEN
      - name: Set up Git authentication
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git

      # 3. Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      # 4. Ensure the results directory exists
      - name: Prepare results directory
        run: mkdir -p ${{ github.workspace }}/$RESULTS_DIR

      # 5. Run the Docker container and execute the simulation
      - name: Run simulation in Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/$RESULTS_DIR:/results_replic \
            ${{ env.DOCKER_IMAGE_NAME }}

      # 6. List the results directory contents
      - name: List results directory contents
        run: ls -la ${{ github.workspace }}/$RESULTS_DIR

      # 7. Commit and push the results generated from the simulation
      - name: Commit and push results
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add $RESULTS_DIR
          git commit -m "Add simulation results" || echo "No changes to commit"
          git push origin main
